header & mobile menu html
IvettaDashkova/Barcelolita pull request #2
Opened 2024-03-19 12:19 UTC by izzwerg

Чистий хтмл хедеру і мобільного меню. Для початку роботи зі стилями чекаю на додавання загальних стилів

2024-03-19 13:07 UTC, IvettaDashkova requested changes
Бачу, що вже щось є, але вчора домовились, що заливатимемо в main вже наближені до завершення секції. Ну або як мінімум такі моменти, які можуть впливати на роботу інших. Тому у випадку з хедером, слід пріорітезувати логіку відпрацювання зміни мови і збереження її стану в локалсторедж. Щоб інші колеги таку поведінку могли враховувати при реалізації їх секцій.

2024-03-20 10:15 UTC, izzwerg commented
Попередньо, все зроблено.
Перемикач мов для прикладу зараз працює в двох варіантах — по дата-атрибутах і по зовнішньому словнику.

2024-03-20 13:43 UTC, IvettaDashkova requested changes

2024-03-20 13:43 UTC, IvettaDashkova commented on src/css/layout/header.css
у вас в загальних стилях` font-family: 'InterTight'; тому font-familу прописуємо лише тоді, коли вони відрізняються від загальних стилів

2024-03-20 13:43 UTC, IvettaDashkova commented on src/css/layout/header.css
те саме і про `  cursor: pointer;` воно у вас вже є в reset.css

2024-03-20 13:43 UTC, IvettaDashkova commented on src/partials/header.html
імпортуй файли js в main.js, щоб уникнути 
```
<script type="module" src="../js/mobile-menu.js"></script>
<script type="module" src="../js/lang-switcher.js"></script>
```

2024-03-20 14:01 UTC, izzwerg commented on src/css/layout/header.css
зробив

2024-03-20 14:01 UTC, izzwerg commented on src/partials/header.html
зробив

2024-03-20 19:43 UTC, merged