Contacts v1.0
IvettaDashkova/Barcelolita pull request #4
Opened 2024-03-19 19:32 UTC by SergeyMyronenko

Add block contacts HTML+CSS. Create adaptive design for 768px and 1440px screen.Also css style for this.
Add footer HTML+CSS, also fof 768px and 1440px screen

2024-03-19 21:00 UTC, kovalsofiia1 commented on src/index.html
> +      <load ="./partials/footer.html" />
Ви напевно трохи неправильно вирішили конфлікти. 
Повернулася секція перед мейном, також футер футер має бути поза мейном.

2024-03-19 21:02 UTC, kovalsofiia1 commented on src/css/styles.css
> +  |============================
тут така ж ситуація як з index.html.
Ви повертаєте видалені частини коду, приберіть їх.

Також подивіться до структури файлів стилів, вони мають бути у папці layout

2024-03-19 21:05 UTC, kovalsofiia1 commented on src/partials/contacts.html
> +<section class="contacts-block">
На секції має бути клас class="section", якщо вам потрібні додаткові стилі зробіть class="section your-class"

2024-03-19 21:07 UTC, kovalsofiia1 commented on src/css/contacts.css
> +  box-sizing: border-box;
Подивіться чи можна забрати box-sizing, оскільки воно є прописано у modern-normalize

2024-03-20 10:22 UTC, kovalsofiia1 commented on src/css/styles.css
> +:root {
ви знову додали цю частину коду при вирішенні конфліктів

2024-03-20 10:22 UTC, kovalsofiia1 commented on src/index.html
> -    <load ="partials/header.html" />
ви видалили імпорт хедера

2024-03-20 13:46 UTC, kovalsofiia1 approved these changes

2024-03-20 19:39 UTC, IvettaDashkova requested changes

2024-03-20 19:39 UTC, IvettaDashkova commented on src/css/layout/contacts.css
бачила у ревію колеги було щодо   `box-sizing: border-box;` . без нього не працює? бо воно є в modern-normalize

2024-03-20 19:39 UTC, IvettaDashkova commented on src/partials/footer.html
ось посилання на Telegram 
`https://t.me/barcelolita`

2024-03-20 19:39 UTC, IvettaDashkova commented on src/css/layout/footer.css
додай на всі посилання ховер ефект як на макеті (дизайнер додала в ui kit)

2024-03-20 19:39 UTC, IvettaDashkova commented on src/css/layout/team.css
на мобілці там бокові падінги 8px на team-info

2024-03-20 19:39 UTC, IvettaDashkova commented on src/partials/footer.html
в номері телефона є невеличкий відступ між + і цифрами

2024-03-20 19:39 UTC, IvettaDashkova commented on src/css/layout/footer.css
в футері на десктопі  відступ від телефона справа менше, ніж на макеті, а відступ міжаватаркою і блоком соц мереж на макеті менше,ніж зараз у нас в футері

2024-03-21 09:30 UTC, IvettaDashkova approved these changes

2024-03-21 09:30 UTC, IvettaDashkova commented on src/partials/team.html
ось тут врахуй ще логіку перемикання мов

2024-03-21 09:30 UTC, merged